import { saveScan } from '../db';
import { IScan } from '../models/Scan';
import { cacheService } from '../services/cache/cacheService';

export const DEMO_SCANS: IScan[] = [
  {
    scanId: 'scan_demo_compliant_001',
    status: 'completed',
    stage: 'completed',
    progress: 100,
    imageUrl: '',
    imageHash: 'hash_demo_compliant',
    barcode: '8901234567890',
    ocr: {
      provider: 'mock',
      rawText: `ABC Biscuits\nNet Wt: 500 g\nMRP ₹120 incl. taxes\nManufactured by: ABC Foods Pvt Ltd, 12 Industrial Area, Mumbai, Maharashtra - 400001\nMfg Date: 08/2025\nConsumer Care: 1800-123-4567, care@abcfoods.in\nLic. No. 11521018000342\nCountry of Origin: India`,
      confidence: 0.98,
      completedAt: new Date(Date.now() - 1000 * 60 * 15),
    },
    fields: {
      productName: { value: 'ABC Biscuits', raw: 'ABC Biscuits', confidence: 0.95, source: 'header_heuristic', found: true },
      manufacturerName: { value: 'ABC Foods Pvt Ltd', raw: 'Manufactured by: ABC Foods Pvt Ltd', confidence: 0.92, source: 'keyword_anchor', found: true },
      manufacturerAddress: { value: '12 Industrial Area, Mumbai, Maharashtra - 400001', raw: '12 Industrial Area, Mumbai, Maharashtra - 400001', confidence: 0.95, source: 'address_pincode', found: true },
      countryOfOrigin: { value: 'India', raw: 'Country of Origin: India', confidence: 0.99, source: 'direct_regex', found: true },
      netQuantityValue: { value: '500', raw: 'Net Wt: 500 g', confidence: 0.95, source: 'regex', found: true },
      netQuantityUnit: { value: 'g', raw: 'Net Wt: 500 g', confidence: 0.95, source: 'regex', found: true },
      monthYear: { value: '08/2025', raw: 'Mfg Date: 08/2025', confidence: 0.95, source: 'regex', found: true },
      mrp: { value: '₹120', raw: 'MRP ₹120 incl. taxes', confidence: 0.96, source: 'regex', found: true },
      consumerCarePhone: { value: '1800-123-4567', raw: '1800-123-4567', confidence: 0.95, source: 'regex', found: true },
      consumerCareEmail: { value: 'care@abcfoods.in', raw: 'care@abcfoods.in', confidence: 0.95, source: 'regex', found: true },
      consumerCareAddress: { value: 'Consumer Care: 1800-123-4567, care@abcfoods.in', raw: 'Consumer Care: 1800-123-4567, care@abcfoods.in', confidence: 0.92, source: 'keyword_anchor', found: true },
      fssaiLicense: { value: '11521018000342', raw: 'Lic. No. 11521018000342', confidence: 0.96, source: 'regex', found: true },
    },
    fieldChecks: [
      { id: 'manufacturer_name_address', label: 'Manufacturer / Packer / Importer Name and Address', status: 'pass', evidence: 'ABC Foods Pvt Ltd, 12 Industrial Area, Mumbai - 400001', message: 'Manufacturer name and address verified with postal code.' },
      { id: 'country_of_origin', label: 'Country of Origin', status: 'pass', evidence: 'Country of Origin: India', message: 'Country of origin explicitly declared.' },
      { id: 'product_name', label: 'Common / Generic Product Name', status: 'pass', evidence: 'ABC Biscuits', message: 'Commodity generic/trade name clearly identified.' },
      { id: 'net_quantity', label: 'Net Quantity', status: 'pass', evidence: 'Net Wt: 500 g', message: 'Standard metric net weight declared.' },
      { id: 'month_year', label: 'Month & Year of Manufacture / Packing', status: 'pass', evidence: 'Mfg Date: 08/2025', message: 'Manufacturing date declared within legal format.' },
      { id: 'mrp', label: 'Maximum Retail Price (MRP)', status: 'pass', evidence: 'MRP ₹120 incl. taxes', message: 'MRP with tax inclusion declared.' },
      { id: 'consumer_care', label: 'Consumer Care Contact Details', status: 'pass', evidence: '1800-123-4567, care@abcfoods.in', message: 'Toll-free consumer grievance helpline and email active.' },
    ],
    complianceScore: 100,
    complianceStatus: 'PASS',
    summary: 'All 7 mandatory Rule 6 declarations found and compliant with Legal Metrology rules.',
    ai: {
      needed: true,
      lowConfidenceFields: [],
      agentEvents: [
        { stage: 'agent:tool_result', agent: 'License_Registry_Agent', tool: 'license_lookup', status: 'completed', result: { status: 'valid', expiryDate: '2027-03-31' }, timestamp: new Date().toISOString() },
      ],
    },
    cacheHit: false,
    demo: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    scanId: 'scan_demo_missing_mrp_002',
    status: 'completed',
    stage: 'completed',
    progress: 100,
    imageHash: 'hash_demo_missing_mrp',
    barcode: '8909876543210',
    ocr: {
      provider: 'mock',
      rawText: `XYZ Chips\nNet Wt: 200 g\nManufactured by: XYZ Snacks Ltd, Sector 4, Rohini, Delhi - 110001\nMfg Date: 07/2025\nConsumer Care: care@xyzsnacks.in, 1800-999-0000`,
      confidence: 0.95,
      completedAt: new Date(Date.now() - 1000 * 60 * 45),
    },
    fields: {
      productName: { value: 'XYZ Chips', raw: 'XYZ Chips', confidence: 0.95, source: 'header_heuristic', found: true },
      manufacturerName: { value: 'XYZ Snacks Ltd', raw: 'Manufactured by: XYZ Snacks Ltd', confidence: 0.92, source: 'keyword_anchor', found: true },
      manufacturerAddress: { value: 'Sector 4, Rohini, Delhi - 110001', raw: 'Sector 4, Rohini, Delhi - 110001', confidence: 0.95, source: 'address_pincode', found: true },
      netQuantityValue: { value: '200', raw: 'Net Wt: 200 g', confidence: 0.95, source: 'regex', found: true },
      netQuantityUnit: { value: 'g', raw: 'Net Wt: 200 g', confidence: 0.95, source: 'regex', found: true },
      monthYear: { value: '07/2025', raw: 'Mfg Date: 07/2025', confidence: 0.95, source: 'regex', found: true },
      mrp: { value: null, raw: null, confidence: 0, source: null, found: false },
      consumerCarePhone: { value: '1800-999-0000', raw: '1800-999-0000', confidence: 0.95, source: 'regex', found: true },
      consumerCareEmail: { value: 'care@xyzsnacks.in', raw: 'care@xyzsnacks.in', confidence: 0.95, source: 'regex', found: true },
    },
    fieldChecks: [
      { id: 'manufacturer_name_address', label: 'Manufacturer / Packer / Importer Name and Address', status: 'pass', evidence: 'XYZ Snacks Ltd, Delhi - 110001', message: 'Manufacturer address verified.' },
      { id: 'country_of_origin', label: 'Country of Origin', status: 'pass', evidence: 'Domestic address detected', message: 'Indian domestic manufacture inferred.' },
      { id: 'product_name', label: 'Common / Generic Product Name', status: 'pass', evidence: 'XYZ Chips', message: 'Commodity name detected.' },
      { id: 'net_quantity', label: 'Net Quantity', status: 'pass', evidence: 'Net Wt: 200 g', message: 'Metric weight declared.' },
      { id: 'month_year', label: 'Month & Year of Manufacture / Packing', status: 'pass', evidence: 'Mfg Date: 07/2025', message: 'Mfg date declared.' },
      { id: 'mrp', label: 'Maximum Retail Price (MRP)', status: 'fail', evidence: 'Not detected', message: 'Critical mandatory MRP declaration inclusive of taxes is missing.' },
      { id: 'consumer_care', label: 'Consumer Care Contact Details', status: 'pass', evidence: 'care@xyzsnacks.in, 1800-999-0000', message: 'Consumer redressal contact present.' },
    ],
    complianceScore: 71,
    complianceStatus: 'FAIL',
    summary: 'Non-compliant (71%). Critical mandatory declarations missing: Maximum Retail Price (MRP).',
    demo: true,
    cacheHit: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45),
  },
  {
    scanId: 'scan_demo_missing_net_qty_003',
    status: 'completed',
    stage: 'completed',
    progress: 100,
    imageHash: 'hash_demo_missing_net_qty',
    ocr: {
      provider: 'mock',
      rawText: `Pure Olive Oil\nMRP ₹450 incl. taxes\nManufactured by: ABC Oils Ltd, Plot 88, Peenya Industrial Area, Bengaluru, Karnataka - 560001\nMfg Date: 06/2025\nConsumer Care: 1800-555-1111, care@abcoils.in`,
      confidence: 0.96,
      completedAt: new Date(Date.now() - 1000 * 60 * 90),
    },
    fields: {
      productName: { value: 'Pure Olive Oil', raw: 'Pure Olive Oil', confidence: 0.95, source: 'header_heuristic', found: true },
      manufacturerName: { value: 'ABC Oils Ltd', raw: 'Manufactured by: ABC Oils Ltd', confidence: 0.92, source: 'keyword_anchor', found: true },
      manufacturerAddress: { value: 'Plot 88, Peenya, Bengaluru - 560001', raw: 'Bengaluru - 560001', confidence: 0.95, source: 'address_pincode', found: true },
      netQuantityValue: { value: null, raw: null, confidence: 0, source: null, found: false },
      netQuantityUnit: { value: null, raw: null, confidence: 0, source: null, found: false },
      monthYear: { value: '06/2025', raw: 'Mfg Date: 06/2025', confidence: 0.95, source: 'regex', found: true },
      mrp: { value: '₹450', raw: 'MRP ₹450 incl. taxes', confidence: 0.96, source: 'regex', found: true },
      consumerCarePhone: { value: '1800-555-1111', raw: '1800-555-1111', confidence: 0.95, source: 'regex', found: true },
    },
    fieldChecks: [
      { id: 'manufacturer_name_address', label: 'Manufacturer / Packer / Importer Name and Address', status: 'pass', evidence: 'ABC Oils Ltd, Bengaluru - 560001', message: 'Manufacturer address verified.' },
      { id: 'country_of_origin', label: 'Country of Origin', status: 'pass', evidence: 'Domestic address detected', message: 'Domestic origin verified.' },
      { id: 'product_name', label: 'Common / Generic Product Name', status: 'pass', evidence: 'Pure Olive Oil', message: 'Generic trade name present.' },
      { id: 'net_quantity', label: 'Net Quantity', status: 'fail', evidence: 'Not detected', message: 'Critical mandatory net quantity declaration is missing.' },
      { id: 'month_year', label: 'Month & Year of Manufacture / Packing', status: 'pass', evidence: 'Mfg Date: 06/2025', message: 'Date declared.' },
      { id: 'mrp', label: 'Maximum Retail Price (MRP)', status: 'pass', evidence: 'MRP ₹450 incl. taxes', message: 'MRP declared.' },
      { id: 'consumer_care', label: 'Consumer Care Contact Details', status: 'pass', evidence: '1800-555-1111', message: 'Helpline present.' },
    ],
    complianceScore: 71,
    complianceStatus: 'FAIL',
    summary: 'Non-compliant (71%). Critical mandatory declarations missing: Net quantity.',
    demo: true,
    cacheHit: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 90),
    updatedAt: new Date(Date.now() - 1000 * 60 * 90),
  },
  {
    scanId: 'scan_demo_missing_care_004',
    status: 'completed',
    stage: 'completed',
    progress: 100,
    imageHash: 'hash_demo_missing_care',
    ocr: {
      provider: 'mock',
      rawText: `Herbal Soap\nNet Wt: 100 g\nMRP ₹45 incl. taxes\nManufactured by: Green Care Products Pvt Ltd, Survey 22, Hinjewadi, Pune, Maharashtra - 411001\nMfg Date: 05/2025`,
      confidence: 0.96,
      completedAt: new Date(Date.now() - 1000 * 60 * 180),
    },
    fields: {
      productName: { value: 'Herbal Soap', raw: 'Herbal Soap', confidence: 0.95, source: 'header_heuristic', found: true },
      manufacturerName: { value: 'Green Care Products Pvt Ltd', raw: 'Manufactured by: Green Care Products', confidence: 0.92, source: 'keyword_anchor', found: true },
      manufacturerAddress: { value: 'Survey 22, Hinjewadi, Pune - 411001', raw: 'Pune - 411001', confidence: 0.95, source: 'address_pincode', found: true },
      netQuantityValue: { value: '100', raw: 'Net Wt: 100 g', confidence: 0.95, source: 'regex', found: true },
      netQuantityUnit: { value: 'g', raw: 'Net Wt: 100 g', confidence: 0.95, source: 'regex', found: true },
      monthYear: { value: '05/2025', raw: 'Mfg Date: 05/2025', confidence: 0.95, source: 'regex', found: true },
      mrp: { value: '₹45', raw: 'MRP ₹45 incl. taxes', confidence: 0.96, source: 'regex', found: true },
      consumerCarePhone: { value: null, raw: null, confidence: 0, source: null, found: false },
      consumerCareEmail: { value: null, raw: null, confidence: 0, source: null, found: false },
      consumerCareAddress: { value: null, raw: null, confidence: 0, source: null, found: false },
    },
    fieldChecks: [
      { id: 'manufacturer_name_address', label: 'Manufacturer / Packer / Importer Name and Address', status: 'pass', evidence: 'Green Care Products, Pune - 411001', message: 'Manufacturer address verified.' },
      { id: 'country_of_origin', label: 'Country of Origin', status: 'pass', evidence: 'Domestic address detected', message: 'Domestic address declared.' },
      { id: 'product_name', label: 'Common / Generic Product Name', status: 'pass', evidence: 'Herbal Soap', message: 'Product trade name present.' },
      { id: 'net_quantity', label: 'Net Quantity', status: 'pass', evidence: 'Net Wt: 100 g', message: 'Metric weight declared.' },
      { id: 'month_year', label: 'Month & Year of Manufacture / Packing', status: 'pass', evidence: 'Mfg Date: 05/2025', message: 'Mfg date declared.' },
      { id: 'mrp', label: 'Maximum Retail Price (MRP)', status: 'pass', evidence: 'MRP ₹45 incl. taxes', message: 'MRP declared.' },
      { id: 'consumer_care', label: 'Consumer Care Contact Details', status: 'fail', evidence: 'Not detected', message: 'Mandatory consumer grievance redressal contact is missing.' },
    ],
    complianceScore: 86,
    complianceStatus: 'PARTIAL',
    summary: 'Partially compliant (86%). Missing or unclear: Consumer care contact details.',
    demo: true,
    cacheHit: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 180),
    updatedAt: new Date(Date.now() - 1000 * 60 * 180),
  },
];

export async function seedDemoData(): Promise<void> {
  console.log('[Seed] Seeding sample compliance scans...');
  for (const scan of DEMO_SCANS) {
    await saveScan(scan);
    if (scan.barcode) {
      cacheService.set(`barcode:${scan.barcode}`, scan);
    }
  }
  console.log(`[Seed] Successfully seeded ${DEMO_SCANS.length} scans`);
}
